# Tell YARN to use Java 17 in Spark containers
spark.yarn.appMasterEnv.JAVA_HOME   /usr/lib/jvm/java-17-openjdk-amd64
spark.executorEnv.JAVA_HOME          /usr/lib/jvm/java-17-openjdk-amd64
 
# Event logging (for Spark History Server)
spark.eventLog.enabled               true
spark.eventLog.dir                   hdfs:///spark-logs
 
# Spark UI: bind to all interfaces so remote browsers can reach :4040
spark.driver.host                    10.92.0.131
spark.ui.host                        0.0.0.0
spark.driver.bindAddress             0.0.0.0
 
# spark history
spark.history.fs.logDirectory        hdfs:///spark-logs
spark.history.ui.port                18080
spark.history.ui.host                0.0.0.0
